### ISSUE TITLE
set triggerdelay didn't work

### ISSUE THREAD

**Issue by idleb** [MyScript/myscript-common-element#1]
I config myscript-math-web triggerdelay property, then it didn't work. I found myscript used `triggerDelay`, but myscript-math-web properties will rename in here, so:

`conf.triggerdelay` should `conf.triggerDelay`, because myscript's configuration use `triggerDelay` 

https://github.com/MyScript/myscript-common-element/blob/7eb63605e9b828cfd1b6a199a05efbad6bde52a0/myscript-common-element.js#L659

`conf.processdelay` same as above

**Comment by benfonty** [comment]
Thank you for your bug report. We will send a fix asap.
